name: Update JSON from XML feed # Název workflow (ponechávám původní, ačkoliv bych doporučil "Update Shoptet XML from XML feed" po úpravě convert.py)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # každou hodinu

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # TOTO JE KLÍČOVÁ ZMĚNA: Předává GITHUB_TOKEN pro autentizaci
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests xmltodict

      - name: Download XML feed
        run: curl -s https://www.krytnamobil.cz/products.xml -o products.xml

      - name: Run script
        run: python convert.py

      - name: Commit and push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          
          # Stáhne nejnovější změny, aby se předešlo konfliktům
          git pull origin main --rebase 
          
          # DŮLEŽITÉ: Zde je stále data.json. Pokud jste upravili convert.py,
          # aby generoval shoptet_products.xml, pak změňte i zde!
          git add data.json 
          
          git commit -m "Update data.json" || echo "No changes to commit"
          
          # Toto je klíčové pro autentizaci push operace
          git push
